#!/bin/bash

MRUN=1000000
MRUN=1

LONG=1
VERBOSE=0

# VERBOSE=1
# LONG=0





# gcc example.c -lfftw3 -Wall -lm -g -Warray-bounds -fsanitize=address -o example -D VERBOSE=0 -D MRUN=1000000 -D FFT_PLAN=d





rm example
gcc example.c -lfftw3 -lm -O3 -o example -D VERBOSE=$VERBOSE -D MRUN=$MRUN -D LONG=$LONG -D FFT_PLAN_MANY=0

#time ./example 
./example


rm example

gcc example.c -lfftw3 -lm -O3 -o example -D VERBOSE=$VERBOSE -D MRUN=$MRUN -D LONG=$LONG -D FFT_PLAN_MANY=1

#time ./example 
./example


