#!/bin/bash

MRUN=1000000
MRUN=1

# gcc example.c -lfftw3 -Wall -lm -g -Warray-bounds -fsanitize=address -o example -D VERBOSE=0 -D MRUN=1000000 -D FFT_PLAN=d

rm example


gcc example_fftw_plan_r2r_2d.c -lfftw3 -lm -O3 -o example -D VERBOSE=0 -D MRUN=$MRUN 

#time ./example 
./example

rm example

gcc example_fftw_plan_many_r2r.c -lfftw3 -lm -O3 -o example -D VERBOSE=0 -D MRUN=$MRUN

#time ./example 
./example
