#!/bin/bash

rm example

echo "Plan many"
# gcc example.c -lfftw3 -Wall -lm -g -Warray-bounds -fsanitize=address -o example -D VERBOSE=0 -D MRUN=1000000 -D FFT_PLAN=MANY
gcc example.c -lfftw3 -lm -O3 -o example -D VERBOSE=0 -D MRUN=1000000 -D FFT_PLAN_MANY=1

time ./example 

echo
rm example
echo

echo "Plan r2r_2d"
# gcc example.c -lfftw3 -Wall -lm -g -Warray-bounds -fsanitize=address -o example -D VERBOSE=0 -D MRUN=1000000 -D FFT_PLAN=d
gcc example.c -lfftw3 -lm -O3 -o example -D VERBOSE=0 -D MRUN=1000000 -D FFT_PLAN_MANY=0

time ./example 
